# Generated by Django 3.2.15 on 2022-11-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trading_account',
            unique_together=set(),
        ),
    ]
